<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.hqwu.commons</groupId>
  <artifactId>hq-commons-parent</artifactId>
  <version>1.2.2-SNAPSHOT</version>
  <packaging>pom</packaging>

  <properties>
    <java.version>1.8</java.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <spring-boot.version>2.4.4</spring-boot.version>
    <commons-io.version>2.6</commons-io.version>
    <maven-surefire-plugin.version>2.22.2</maven-surefire-plugin.version>
    <mybatis-plus.version>3.4.1</mybatis-plus.version>
    <mybatis.version>3.5.6</mybatis.version>
    <mybatis-boot.version>2.1.4</mybatis-boot.version>

    <hq-cp.version>1.2.0-SNAPSHOT</hq-cp.version>
    <hq-mybatis-plus-extension.version>1.2.0-SNAPSHOT</hq-mybatis-plus-extension.version>
    <hq-spring-webmvc.version>1.2.0-SNAPSHOT</hq-spring-webmvc.version>
  </properties>

  <scm>
    <developerConnection>scm:git:https://bitbucket.org/alphapayit/common-utils.git</developerConnection>
    <url>https://bitbucket.org/alphapayit/common-utils</url>
    <tag>HEAD</tag>
  </scm>

  <modules>
    <module>hq-utils</module>
    <module>hq-cp</module>
    <module>hq-cp-boot-starter</module>
    <module>hq-mybatis-plus-extension</module>
    <module>hq-spring-webmvc</module>
  </modules>

  <repositories>
    <repository>
      <id>flash-nexus</id>
      <name>Flash Nexus Repository</name>
      <url>https://nexus.flash.ca/nexus/content/groups/public/</url>
    </repository>
  </repositories>

  <distributionManagement>
    <repository>
      <id>flash-releases</id>
      <name>Nexus-releases-repositories</name>
      <url>https://nexus.flash.ca/nexus/content/repositories/releases/</url>
    </repository>
    <snapshotRepository>
      <id>flash-nexus</id>
      <name>Nexus-snapshots-repositories</name>
      <url>https://nexus.flash.ca/nexus/content/repositories/snapshots/</url>
    </snapshotRepository>
  </distributionManagement>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>${spring-boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>commons-io</groupId>
        <artifactId>commons-io</artifactId>
        <version>${commons-io.version}</version>
      </dependency>
      <dependency>
        <groupId>com.baomidou</groupId>
        <artifactId>mybatis-plus</artifactId>
        <version>${mybatis-plus.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${maven-surefire-plugin.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-release-plugin</artifactId>
        <configuration>
          <arguments>-Dmaven.javadoc.skip=true -DskipTests</arguments>
          <tagNameFormat>v@{project.version}</tagNameFormat>
          <goals>deploy</goals>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.2.1</version>
        <executions>
          <execution>
            <id>attach-sources</id>
            <phase>verify</phase>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>